name: generate_doxygen_docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  generate_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout action
        uses: actions/checkout@v3

      - name: Doxygen action
        uses: mattnotmitt/doxygen-action@1.9.3

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
